### PR TITLE
Show dev, channel and microwave config when configs conflict.

### LINKED ISSUE #272: when qubit sequencer has conflicting microwave configurations, tell me _what_ the conflict is
The following error message came from the qubit sequencer:

```
Error: (0) java.lang.IllegalArgumentException: requirement failed: Conflicting microwave configurations for source 'Vince GPIB Bus - GPIB0::4::INSTR'
	at scala.Predef$.require(Predef.scala:219)
	at org.labrad.qubits.QubitContext$$anonfun$build_sequence$1.apply(QubitContext.scala:934)
	at org.labrad.qubits.QubitContext$$anonfun$build_sequence$1.apply(QubitContext.scala:923)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.labrad.qubits.QubitContext.build_sequence(QubitContext.scala:923)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.labrad.handlers.ZeroArgVoidHandler.handle(ZeroArgVoidHandler.java:16)
	at org.labrad.ContextManager.processRequest(ContextManager.java:143)
	at org.labrad.ContextManager.access$100(ContextManager.java:15)
	at org.labrad.ContextManager$RequestProcessor.run(ContextManager.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
 [payload=None]
```

It would be more useful if were to give information on the conflict.

### PR DESCRIPTION
**Pull request by maffoo**
Fixes #272

### CODE REVIEW

File: QubitServer/src/main/scala/org/labrad/qubits/QubitContext.scala [hunk 1]
```diff
@@ -878,24 +878,39 @@ class QubitContext(cxn: ServerConnection, resources: () => Resources) extends Se
...
+    val configsBySrc = (for {
+      dev <- expt.devices
+      chan <- dev.getChannels[IqChannel]
+    } yield {
+      val src = chan.getMicrowaveSource()
+      val config = chan.getMicrowaveConfig()
+      require(config != null, s"No microwaves configured: dev=${dev.name}, channel=${chan.name}")
+      src -> (dev, chan, config)
+    }).groupBy { case (src, chans) => src }
+      .mapValues(_.map { case (src, info) => info })
```
Comment (pomalley) [inline QubitServer/src/main/scala/org/labrad/qubits/QubitContext.scala]: This threw me for a loop because (1) I wasn't familiar with `groupBy` and (2) it calls the triple `(dev, chan, config)` `chans` in the groupBy and `info` in the mapValues so it wasn't obvious they were the same thing.

**Comment by pomalley** [comment]
Would be good to test this out, of course--maybe just get someone to temporarily copy their channels key to two qubits and see that you get a decent error message.

After that, LGTM.
